[106]: Set app locale to system locale on first launch
salomaoluiz/BuyIt pull request #114
Opened 2021-02-13 03:47 UTC by sanjeevyadavIT

Changes:

1. Add `react-native-localize` library
2. When app first launch, use the system locale to set app locale if supported by app
3. Write new tests
4. Update `enUs` to `en-US` and `ptBR` to `pt-BR` everywhere

2021-02-13 23:38 UTC, salomaoluiz requested changes
Hi @sanjeevyadavIT , thanks for your contributions, I just request two changes, it is littles mistakes on portuguese translation.

2021-02-13 23:38 UTC, salomaoluiz commented on src/locales/__tests__/index.test.ts
> +  test('caso não possua o locale no AsyncStorage, deve setar o default de react-native-loalize', async () => {
here is just a grammar mistake, in Portuguese on this case, we use "... do react-native-localize'. And you wrote "loalize" here  and in the above line.

2021-02-13 23:38 UTC, salomaoluiz commented on src/locales/__tests__/index.test.ts
> +  test('caso não possua o locale no AsyncStorage, localidade do sistema não é suportado, deve configurá-lo como pt-BR', async () => {
Here you can write something like this:
"caso não possua o locale no AsyncStorage e o locale não é suportado pelo sistema, deve configurá-lo como pt-BR"

2021-02-14 05:59 UTC, sanjeevyadavIT commented
I have made the requested changes

2021-02-14 21:44 UTC, salomaoluiz approved these changes

2021-02-14 21:48 UTC, salomaoluiz requested changes
Another thing, in the commit, add a # on issue ID, because this way are created a link on commit to issue, your commit will be this way: [#106]: Set app locale to system locale on first launch

2021-02-15 21:50 UTC, sanjeevyadavIT commented
Hi, I have change the commit message

2021-02-17 09:16 UTC, salomaoluiz approved these changes

2021-02-17 09:17 UTC, merged